name: Yandex Cloud Auto-Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Yandex Cloud Container Registry
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YANDEX_SA_JSON }}

      - name: Build and push Docker image
        env:
          CR_REGISTRY: crp357h6d94o1kcgiqhv
          CR_REPOSITORY: english_project
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:user${IMAGE_TAG} .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:user${IMAGE_TAG}

      - name: Connect to Yandex Cloud VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}

      - name: Deploy to Yandex Cloud
        env:
          YANDEX_KEY: ${{ secrets.YANDEX_KEY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sudo docker login --username oauth --password $YANDEX_KEY cr.yandex
          sudo docker pull cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:user${IMAGE_TAG}
          sudo docker stop your-container-name || true
          sudo docker rm your-container-name || true
          sudo docker run -d -p 80:80 --name your-container-name cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:user${IMAGE_TAG}
